projects:
  dbpedia-en:
    shaclFile: ./src/config/dbpedia/config.ttl
    sparqlEndpoint: https://dbpedia.org/sparql
    endpoints-agents:
      MISTRAL_AGENT_ID_query_2_text: ag:33fd9714:20250507:untitled-agent:d1fc8155
      MISTRAL_AGENT_ID_text_2_query: ag:33fd9714:20250624:text2query:a7d9abe6
    domains:
      - sparna-git.github.io
