log:
  directory: ./logs
projects:
  dbpedia-en:
    shaclFile: ./config/dbpedia-en/config.ttl
    sparqlEndpoint: https://dbpedia.org/sparql
    domains:
      - sparna-git.github.io
    cache:
      urilookup: ./cache/dbpedia-en/urilookup_cache.json
    reconciliation:
      implementation: SparqlReconcileServiceV13
      cacheSize: 1000
      maxResults: 2
    text2query:
      implementation: MistralText2QueryService
      agentId: ag_019c8a5149a076f48d90b303514760d6
    query2text:
      implementation: MistralQuery2TextService
      agentId: ag_019c8b1bad56750d95e1b91e7d2a8ce8
    t2qPromptGenerator:
      implementation: T2QPromptGenerator
    q2tPromptGenerator:
      implementation: Q2TPromptGenerator
  demo-ep:
    shaclFile: ./config/demo-ep/config.ttl
    sparqlEndpoint: http://graphdb.sparna.fr/repositories/endorse2025
    domains:
      - sparna-git.github.io
    cache:
      urilookup: ./cache/demo-ep/urilookup_cache.json
    reconciliation:
      implementation: SparqlReconcileServiceV13
      cacheSize: 1000
      maxResults: 2
    text2query:
      implementation: MistralText2QueryService
      agentId: ag_019c8ea6b01e767ab664186d5749eb6f
    query2text:
      implementation: MistralQuery2TextService
      agentId: ag:33fd9714:20250507:untitled-agent:d1fc8155
    t2qPromptGenerator:
      implementation: T2QPromptGenerator
    q2tPromptGenerator:
      implementation: Q2TPromptGenerator
